// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: boards.sql

package sqlcgen

import (
	"context"
	"time"
)

const deleteBoard = `-- name: DeleteBoard :exec
DELETE FROM boards WHERE id = $1::uuid
`

func (q *Queries) DeleteBoard(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteBoard, id)
	return err
}

const getBoard = `-- name: GetBoard :one
SELECT id::text AS id, owner_id::text AS owner_id, title, created_at, updated_at
FROM boards
WHERE id = $1::uuid
`

type GetBoardRow struct {
	ID        string
	OwnerID   string
	Title     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetBoard(ctx context.Context, id string) (GetBoardRow, error) {
	row := q.db.QueryRow(ctx, getBoard, id)
	var i GetBoardRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBoard = `-- name: InsertBoard :exec
INSERT INTO boards (id, owner_id, title, created_at, updated_at)
VALUES ($1::uuid, $2::uuid, $3, $4, $5)
`

type InsertBoardParams struct {
	ID        string
	OwnerID   string
	Title     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) InsertBoard(ctx context.Context, arg InsertBoardParams) error {
	_, err := q.db.Exec(ctx, insertBoard,
		arg.ID,
		arg.OwnerID,
		arg.Title,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertMember = `-- name: InsertMember :exec
INSERT INTO board_members (board_id, user_id, role)
VALUES ($1::uuid, $2::uuid, $3)
`

type InsertMemberParams struct {
	BoardID string
	UserID  string
	Role    string
}

func (q *Queries) InsertMember(ctx context.Context, arg InsertMemberParams) error {
	_, err := q.db.Exec(ctx, insertMember, arg.BoardID, arg.UserID, arg.Role)
	return err
}

const listBoardsForUser = `-- name: ListBoardsForUser :many
SELECT b.id::text AS id, b.owner_id::text AS owner_id, b.title, b.created_at, b.updated_at
FROM boards b
JOIN board_members m ON m.board_id = b.id
WHERE m.user_id = $1::uuid
ORDER BY b.created_at
`

type ListBoardsForUserRow struct {
	ID        string
	OwnerID   string
	Title     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) ListBoardsForUser(ctx context.Context, userID string) ([]ListBoardsForUserRow, error) {
	rows, err := q.db.Query(ctx, listBoardsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBoardsForUserRow{}
	for rows.Next() {
		var i ListBoardsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const membershipByBoard = `-- name: MembershipByBoard :one
SELECT board_id::text AS board_id, role
FROM board_members
WHERE board_id = $1::uuid AND user_id = $2::uuid
`

type MembershipByBoardParams struct {
	BoardID string
	UserID  string
}

type MembershipByBoardRow struct {
	BoardID string
	Role    string
}

func (q *Queries) MembershipByBoard(ctx context.Context, arg MembershipByBoardParams) (MembershipByBoardRow, error) {
	row := q.db.QueryRow(ctx, membershipByBoard, arg.BoardID, arg.UserID)
	var i MembershipByBoardRow
	err := row.Scan(&i.BoardID, &i.Role)
	return i, err
}

const membershipByCard = `-- name: MembershipByCard :one
SELECT col.board_id::text AS board_id, m.role
FROM cards cd
JOIN columns col ON col.id = cd.column_id
JOIN board_members m ON m.board_id = col.board_id AND m.user_id = $1::uuid
WHERE cd.id = $2::uuid
`

type MembershipByCardParams struct {
	UserID string
	CardID string
}

type MembershipByCardRow struct {
	BoardID string
	Role    string
}

func (q *Queries) MembershipByCard(ctx context.Context, arg MembershipByCardParams) (MembershipByCardRow, error) {
	row := q.db.QueryRow(ctx, membershipByCard, arg.UserID, arg.CardID)
	var i MembershipByCardRow
	err := row.Scan(&i.BoardID, &i.Role)
	return i, err
}

const membershipByColumn = `-- name: MembershipByColumn :one
SELECT c.board_id::text AS board_id, m.role
FROM columns c
JOIN board_members m ON m.board_id = c.board_id AND m.user_id = $1::uuid
WHERE c.id = $2::uuid
`

type MembershipByColumnParams struct {
	UserID   string
	ColumnID string
}

type MembershipByColumnRow struct {
	BoardID string
	Role    string
}

func (q *Queries) MembershipByColumn(ctx context.Context, arg MembershipByColumnParams) (MembershipByColumnRow, error) {
	row := q.db.QueryRow(ctx, membershipByColumn, arg.UserID, arg.ColumnID)
	var i MembershipByColumnRow
	err := row.Scan(&i.BoardID, &i.Role)
	return i, err
}

const updateBoardTitle = `-- name: UpdateBoardTitle :exec
UPDATE boards SET title = $1, updated_at = $2
WHERE id = $3::uuid
`

type UpdateBoardTitleParams struct {
	Title     string
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) UpdateBoardTitle(ctx context.Context, arg UpdateBoardTitleParams) error {
	_, err := q.db.Exec(ctx, updateBoardTitle, arg.Title, arg.UpdatedAt, arg.ID)
	return err
}
