// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cards.sql

package sqlcgen

import (
	"context"
	"time"
)

const deleteCard = `-- name: DeleteCard :exec
DELETE FROM cards WHERE id = $1::uuid
`

func (q *Queries) DeleteCard(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteCard, id)
	return err
}

const getCard = `-- name: GetCard :one
SELECT id::text AS id, column_id::text AS column_id, title, description, position, created_at, updated_at
FROM cards
WHERE id = $1::uuid
`

type GetCardRow struct {
	ID          string
	ColumnID    string
	Title       string
	Description string
	Position    string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetCard(ctx context.Context, id string) (GetCardRow, error) {
	row := q.db.QueryRow(ctx, getCard, id)
	var i GetCardRow
	err := row.Scan(
		&i.ID,
		&i.ColumnID,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCard = `-- name: InsertCard :exec
INSERT INTO cards (id, column_id, title, description, position, created_at, updated_at)
VALUES ($1::uuid, $2::uuid, $3, $4,
        $5, $6, $7)
`

type InsertCardParams struct {
	ID          string
	ColumnID    string
	Title       string
	Description string
	Position    string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) InsertCard(ctx context.Context, arg InsertCardParams) error {
	_, err := q.db.Exec(ctx, insertCard,
		arg.ID,
		arg.ColumnID,
		arg.Title,
		arg.Description,
		arg.Position,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listCardsByBoard = `-- name: ListCardsByBoard :many
SELECT cd.id::text AS id, cd.column_id::text AS column_id, cd.title, cd.description, cd.position,
       cd.created_at, cd.updated_at
FROM cards cd
JOIN columns col ON col.id = cd.column_id
WHERE col.board_id = $1::uuid
ORDER BY cd.column_id, cd.position
`

type ListCardsByBoardRow struct {
	ID          string
	ColumnID    string
	Title       string
	Description string
	Position    string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) ListCardsByBoard(ctx context.Context, boardID string) ([]ListCardsByBoardRow, error) {
	rows, err := q.db.Query(ctx, listCardsByBoard, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCardsByBoardRow{}
	for rows.Next() {
		var i ListCardsByBoardRow
		if err := rows.Scan(
			&i.ID,
			&i.ColumnID,
			&i.Title,
			&i.Description,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCardsByColumn = `-- name: ListCardsByColumn :many
SELECT id::text AS id, column_id::text AS column_id, title, description, position, created_at, updated_at
FROM cards
WHERE column_id = $1::uuid
ORDER BY position
`

type ListCardsByColumnRow struct {
	ID          string
	ColumnID    string
	Title       string
	Description string
	Position    string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) ListCardsByColumn(ctx context.Context, columnID string) ([]ListCardsByColumnRow, error) {
	rows, err := q.db.Query(ctx, listCardsByColumn, columnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCardsByColumnRow{}
	for rows.Next() {
		var i ListCardsByColumnRow
		if err := rows.Scan(
			&i.ID,
			&i.ColumnID,
			&i.Title,
			&i.Description,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCardContent = `-- name: UpdateCardContent :exec
UPDATE cards SET title = $1, description = $2, updated_at = $3
WHERE id = $4::uuid
`

type UpdateCardContentParams struct {
	Title       string
	Description string
	UpdatedAt   time.Time
	ID          string
}

func (q *Queries) UpdateCardContent(ctx context.Context, arg UpdateCardContentParams) error {
	_, err := q.db.Exec(ctx, updateCardContent,
		arg.Title,
		arg.Description,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateCardPosition = `-- name: UpdateCardPosition :exec
UPDATE cards SET column_id = $1::uuid, position = $2, updated_at = now()
WHERE id = $3::uuid
`

type UpdateCardPositionParams struct {
	ColumnID string
	Position string
	ID       string
}

func (q *Queries) UpdateCardPosition(ctx context.Context, arg UpdateCardPositionParams) error {
	_, err := q.db.Exec(ctx, updateCardPosition, arg.ColumnID, arg.Position, arg.ID)
	return err
}
