// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: columns.sql

package sqlcgen

import (
	"context"
	"time"
)

const deleteColumn = `-- name: DeleteColumn :exec
DELETE FROM columns WHERE id = $1::uuid
`

func (q *Queries) DeleteColumn(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteColumn, id)
	return err
}

const getColumn = `-- name: GetColumn :one
SELECT id::text AS id, board_id::text AS board_id, title, position, created_at
FROM columns
WHERE id = $1::uuid
`

type GetColumnRow struct {
	ID        string
	BoardID   string
	Title     string
	Position  string
	CreatedAt time.Time
}

func (q *Queries) GetColumn(ctx context.Context, id string) (GetColumnRow, error) {
	row := q.db.QueryRow(ctx, getColumn, id)
	var i GetColumnRow
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Title,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const insertColumn = `-- name: InsertColumn :exec
INSERT INTO columns (id, board_id, title, position, created_at)
VALUES ($1::uuid, $2::uuid, $3, $4, $5)
`

type InsertColumnParams struct {
	ID        string
	BoardID   string
	Title     string
	Position  string
	CreatedAt time.Time
}

func (q *Queries) InsertColumn(ctx context.Context, arg InsertColumnParams) error {
	_, err := q.db.Exec(ctx, insertColumn,
		arg.ID,
		arg.BoardID,
		arg.Title,
		arg.Position,
		arg.CreatedAt,
	)
	return err
}

const listColumns = `-- name: ListColumns :many
SELECT id::text AS id, board_id::text AS board_id, title, position, created_at
FROM columns
WHERE board_id = $1::uuid
ORDER BY position
`

type ListColumnsRow struct {
	ID        string
	BoardID   string
	Title     string
	Position  string
	CreatedAt time.Time
}

func (q *Queries) ListColumns(ctx context.Context, boardID string) ([]ListColumnsRow, error) {
	rows, err := q.db.Query(ctx, listColumns, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListColumnsRow{}
	for rows.Next() {
		var i ListColumnsRow
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Title,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateColumnPosition = `-- name: UpdateColumnPosition :exec
UPDATE columns SET position = $1 WHERE id = $2::uuid
`

type UpdateColumnPositionParams struct {
	Position string
	ID       string
}

func (q *Queries) UpdateColumnPosition(ctx context.Context, arg UpdateColumnPositionParams) error {
	_, err := q.db.Exec(ctx, updateColumnPosition, arg.Position, arg.ID)
	return err
}

const updateColumnTitle = `-- name: UpdateColumnTitle :exec
UPDATE columns SET title = $1 WHERE id = $2::uuid
`

type UpdateColumnTitleParams struct {
	Title string
	ID    string
}

func (q *Queries) UpdateColumnTitle(ctx context.Context, arg UpdateColumnTitleParams) error {
	_, err := q.db.Exec(ctx, updateColumnTitle, arg.Title, arg.ID)
	return err
}
