// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Board struct {
	ID        string
	OwnerID   string
	Title     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type BoardMember struct {
	BoardID   string
	UserID    string
	Role      string
	CreatedAt time.Time
}

type Card struct {
	ID          string
	ColumnID    string
	Title       string
	Description string
	Position    string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Column struct {
	ID        string
	BoardID   string
	Title     string
	Position  string
	CreatedAt time.Time
}

type RefreshToken struct {
	ID        string
	UserID    string
	TokenHash []byte
	FamilyID  string
	ExpiresAt time.Time
	RevokedAt pgtype.Timestamptz
	CreatedAt time.Time
}

type User struct {
	ID           string
	Email        string
	PasswordHash string
	DisplayName  string
	CreatedAt    time.Time
}
