// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	DeleteBoard(ctx context.Context, id string) error
	DeleteCard(ctx context.Context, id string) error
	DeleteColumn(ctx context.Context, id string) error
	GetBoard(ctx context.Context, id string) (GetBoardRow, error)
	GetCard(ctx context.Context, id string) (GetCardRow, error)
	GetColumn(ctx context.Context, id string) (GetColumnRow, error)
	InsertBoard(ctx context.Context, arg InsertBoardParams) error
	InsertCard(ctx context.Context, arg InsertCardParams) error
	InsertColumn(ctx context.Context, arg InsertColumnParams) error
	InsertMember(ctx context.Context, arg InsertMemberParams) error
	ListBoardsForUser(ctx context.Context, userID string) ([]ListBoardsForUserRow, error)
	ListCardsByBoard(ctx context.Context, boardID string) ([]ListCardsByBoardRow, error)
	ListCardsByColumn(ctx context.Context, columnID string) ([]ListCardsByColumnRow, error)
	ListColumns(ctx context.Context, boardID string) ([]ListColumnsRow, error)
	MembershipByBoard(ctx context.Context, arg MembershipByBoardParams) (MembershipByBoardRow, error)
	MembershipByCard(ctx context.Context, arg MembershipByCardParams) (MembershipByCardRow, error)
	MembershipByColumn(ctx context.Context, arg MembershipByColumnParams) (MembershipByColumnRow, error)
	UpdateBoardTitle(ctx context.Context, arg UpdateBoardTitleParams) error
	UpdateCardContent(ctx context.Context, arg UpdateCardContentParams) error
	UpdateCardPosition(ctx context.Context, arg UpdateCardPositionParams) error
	UpdateColumnPosition(ctx context.Context, arg UpdateColumnPositionParams) error
	UpdateColumnTitle(ctx context.Context, arg UpdateColumnTitleParams) error
}

var _ Querier = (*Queries)(nil)
