version: "2"

linters:
  default: standard # errcheck, govet, ineffassign, staticcheck, unused
  enable:
    - copyloopvar
    - errorlint
    - gocritic
    - misspell
    - nolintlint
    - revive
    - unconvert
    - unparam

formatters:
  enable:
    - gofmt
    - goimports
